version: '3.8'

volumes:
  postgresql-ci-db-data:


services:
  db:
    container_name: postgresql-ci-db
    image: postgres:15
    volumes:
      - postgresql-ci-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 1s

  api:
    container_name: postgresql-ci-api
    build: .
    volumes:
      - .:/code # for auto reload
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
